// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 5.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'todo';

  static const String assets_image_avatar1_png = 'assets/image/avatar1.png';
  static const String todo$assets_image_avatar1_png = 'packages/todo/assets/image/avatar1.png';

  static const String assets_image_fb_png = 'assets/image/fb.png';
  static const String todo$assets_image_fb_png = 'packages/todo/assets/image/fb.png';

  static const String assets_image_frame1_png = 'assets/image/frame1.png';
  static const String todo$assets_image_frame1_png = 'packages/todo/assets/image/frame1.png';

  static const String assets_image_gg_png = 'assets/image/gg.png';
  static const String todo$assets_image_gg_png = 'packages/todo/assets/image/gg.png';

  static const String assets_image_ig_png = 'assets/image/ig.png';
  static const String todo$assets_image_ig_png = 'packages/todo/assets/image/ig.png';
}
